language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/registration

node_js:  
  - "12"

before_script:
  - psql -c 'create database  registration;' -U postgres
  - psql -U postgres -d registration -a -f tables.sql

services:
  - postgresql